#pragma config(Motor,  port2,           driveL,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           arm,           tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           boxS,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           claw,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           rotate1,       tmotorServoStandard, openLoop, reversed)
#pragma config(Motor,  port7,           rotate2,       tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           box,           tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           driveR,        tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*WARNING DON'T FIX THE FORMATTING

    /***********************************\
   /                  The                \
  /           Home of Programming         \
 /                                         \
/                                           \
| Right joystick =  Drive                   |
|                                           |
| Button 6U + left joystick = arm up & down |
|                                           |
| Button 6D = Holds the arm position        |
|                                           |
| Button 5U = Open Dumper                   |
|                                           |
| Button 5D = Close Dumper                  |
|*******************************************/

/*********************************************************\
|This is the best code ;) for the 2015 BEST competition.  |
|Written by: Programmers. If you need help programming,   |
|ask the main programmers(Dalton,and George).             |
|They would be happy to help you, but if they cannot help |
|for any reason they will assign a subordinate to assist  |
|you.                                                     |
|                                               Thank You.|
\*********************************************************/


int leftX = 0;
int leftY = 0;
int rightY = 0;
int rightX = 0;
int thresh = 15;
int stage = 0;
bool macro = false;
const bool on = true;

task drive() { //This is the drive task. This is here so that we can drive and operate the manipulator at the same time.
	while(on) {
		motor[driveL] = -rightY - rightX;
		motor[driveR] = rightY - rightX;
	}
}

task manipulator() { //This is the manipulator task. This allows us to opperate the manipulator and drive simutaneously.

	motor[claw] = 100; //This is code for opening and rotating the air filter claw.
	wait1Msec(400);
	motor[rotate1] = 95;

	while(on) { //This states that when the robot is on execute the preceeding comands.
		if(vexRT[Btn6U]) { //This is the code for the arm. It allows us to operate the arm.
			if(vexRT[Btn6D]) { //Holding this button prevents the arm from drifting downward.
				motor[arm] = leftY + 20;
				} else {
				motor[arm] = leftY;
			}
			} else if(vexRT[Btn6D]) { //This is code for the anti-drift button
			motor[arm] = 20;
			} else {
			motor[arm] = 0;
		}

		if(vexRT[Btn7D]) {
			motor[claw] = motor[claw] + 1;
			wait1Msec(1);
			} else if(vexRT[Btn7U]) {
			motor[claw] = motor[claw] - 1;
			wait1Msec(1);
		}

		if(vexRT[Btn7L]) { //This is servo code used for testing a prototype design.
			motor[rotate1] = -75;
			//motor[rotate1] = motor[rotate1] + 1;
			wait1Msec(500);
			if(stage == 0) {
				motor[claw] = -100;
				stage = 1;
			}
		} else if(vexRT[Btn7R]) {
			motor[rotate1] = 95;
			//motor[rotate1] = motor[rotate1] - 1;
			//wait1Msec(2);
		}

/*		if(vexRT[Btn5U] && stage == 0) {
			motor[boxS] = -55;
			macro = true;
			stage = 1;
		} else if(vexRT[Btn5D] && stage == 1 && macro == false) {
			motor[boxS] = -127;
			stage = 2;
		} else if(!vexRT[Btn5U] && macro == true && stage == 1) {
			macro = false;
		}
*/

/*		if(vexRT[Btn5U]) {
			motor[boxS] = -55;
			stage = 1;
		} else if(vexRT[Btn5D]) {
			motor[boxS] = -127;
			stage = 2;
		} else {
			motor[boxS] = 0;
			stage = 0;
		}
*/

		if(vexRT[Btn5U] && vexRT[Btn5D] && stage == 0) { //This code is used for closing the box.
			motor[boxS] = -55;
			stage = 1;
			macro = true;
		} else if(vexRT[Btn5U] && vexRT[Btn5D] && stage == 1 && macro == false) {
			motor[boxS] = -127;
			stage = 2;
			macro = true;
		} else if(vexRT[Btn5U] && vexRT[Btn5D] && stage == 2 && macro == false) {
			motor[boxS] = 0;
			stage = 0;
			macro = true;
		} else if(macro == true) {
			if(vexRT[Btn5U]) {
			} else if(vexRT[Btn5D]) {
			} else {
				macro = false;
			}
		}

/*		if(!vexRT[Btn5U] && macro == true || !vexRT[Btn5D] && macro == true) {
			macro = false;
		}
*
		if(vexRT[Btn7U]) {
			motor[rotate2] = motor[rotate2] - 1;
			wait1Msec(1);
			} else if(vexRT[Btn7D]) {
			motor[rotate2] = motor[rotate2] + 1;
			wait1Msec(1);
		}
*/
		if(vexRT[Btn8L]) { //This is servo code that is dedicated to a claw.
			motor[rotate2] = 127;
			stage = 0;
		} else if(vexRT[Btn8R]) {
			motor[rotate2] = 0;
		}

		if(vexRT[Btn5D]) { //This code is used for opening the box.
			motor[box] = 120;
			} else if(vexRT[Btn5U]) {
			motor[box] = -120;
			} else {
			motor[box] = 0;
		}

		if(vexRT[Btn8D] && macro == false) { //This is macro code. This allows the driver to press one button to raise the arm by a specific ammount.
			macro = true;
			motor[arm] = 100;
			wait1Msec(80);
			motor[arm] = 0;
			} else if(vexRT[Btn8U] && macro == false) {
			macro = true;
			motor[arm] = 75;
			wait1Msec(80);
			motor[arm] = 0;
			} else if(macro == true && !vexRT[Btn8D] && !vexRT[Btn8U]) {
			macro = false;
		}

/*		if(vexRT[Btn7L] && macro == false) {
			macro = true;
			motor[arm] = 100;
			motor[box] = -120;
			wait1Msec(150);
			motor[arm] = 0;
			wait1Msec(500);
			motor[box] = 0;
			} else if(macro == true && !vexRT[Btn7L]) {
			macro = false;
		}*/
	}
}

task main() { //This holds the main tasks the robot initially starts with.
	startTask(drive); //This starts the drivetask so we can actually drive the robot.
	startTask(manipulator); //This starts the manipulator task. Without this, the manipulator would not function.
	while(on) {
		rightX = vexRT(Ch1);
		if(abs(rightX)<thresh){ //This adds a deadzone in the controller's right X axis, so that drivers have more reliable control of the robot.
			rightX = 0;
		}
		rightY = vexRT(Ch2);
		if(abs(rightY)<thresh){ //This adds a deadzone in the controller's right Y axis, so that drivers have more reliable control of the robot.
			rightY = 0;
		}
		leftY = vexRT(Ch3);
		if(abs(leftY)<thresh){ //This adds a deadzone in the controller's left Y axis, so that drivers have more reliable control of the robot.
			leftY = 0;
		}
		leftX = vexRT(Ch4);
		if(abs(leftX)<thresh){ //This adds a deadzone in the controller's left X axis, so that drivers have more reliable control of the robot.
			leftX = 0;
		}
	}
}
//BANG!!! and thats how its done.
