#pragma config(Motor,  port2,           driveL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           clawR,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           clawL,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           cart,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           cart2,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           driveR,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftX = 0;
int leftY = 0;
int rightY = 0;
int rightX = 0;
const bool on = true;

task drive() {
	while(on) {
		motor[driveL] = rightY + rightX;
		motor[driveR] = rightY - rightX;
	}
}

task manipulator() {
	while(on) {
		if(vexRT[Btn6U]) {
			motor[arm] = leftY;
			} else {
			motor[arm] = 0;
		}

		if(vexRT[Btn8L]) {
			if(motor[clawL] < 130) {
				motor[clawL] = motor[clawL] + 1;
				wait1Msec(1);
			}
			} else if(vexRT[Btn8R]) {
			if(motor[clawL] <- 130) {
				motor[clawL] = motor[clawL] - 1;
				wait1Msec(1);
			}
		}

		if(vexRT[Btn8U]) {
			motor[cart] = motor[cart] + 1;
			wait1Msec(1);
			} else if(vexRT[Btn8D]) {
			motor[cart] = motor[cart] - 1;
			wait1Msec(1);
		}

		if(vexRT[Btn7U]) {
			motor[cart2] = motor[cart2] - 1;
			wait1Msec(1);
			} else if(vexRT[Btn7D]) {
			motor[cart2] = motor[cart2] + 1;
			wait1Msec(1);
		}
	}
}

task main() {
	startTask(drive);
	startTask(manipulator);
	while(on) {
		rightX = vexRT(Ch1);
		rightY = vexRT(Ch2);
		leftY = vexRT(Ch3);
		leftX = vexRT(Ch4);
	}
}
