#pragma config(Motor,  port2,           driveL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           scooper,       tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           clawL,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           cart,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           cart2,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           driveR,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*WARNING DON'T FIX THE FORMATTING

    /***********************************\
	 /                  The                \
  /           Home of Programming         \
 /             (I Lost the Game)           \
/                                           \
| Right joystick =  Drive                   |
|                                           |
| Button 6U + left joystick = arm up & down |
|                                           |
| Button 8L = open, Button 8R = Close       |
|                                           |
|                                           |
|*******************************************/

/*********************************************************\
|This is the best code ;) for the 2015 BEST competition.  |
|Written by: Programmers. If you need help programming,   |
|ask the main programmers(Dalton,and George).             |
|They would be happy to help you, but if they cannot help |
|for any reason they will assign a subordinate to assist  |
|you.                                                     |
|                                               Thank You.|
\*********************************************************/


int leftX = 0;
int leftY = 0;
int rightY = 0;
int rightX = 0;
const bool on = true;

task drive() {
	while(on) {
		motor[driveL] = -rightY - rightX;
		motor[driveR] = rightY - rightX;
	}
}

task manipulator() {
	while(on) {
		if(vexRT[Btn6U]) {
			motor[arm] = leftY;
			} else {
			motor[arm] = 0;
		}

		if(vexRT[Btn8L]) {

			motor[clawL] = motor[clawL] + 1;
			wait1Msec(1);
			} else if(vexRT[Btn8R]) {
			motor[clawL] = motor[clawL] - 1;
			wait1Msec(1);
		}

		if(vexRT[Btn7L]) {

			motor[scooper] = motor[scooper] + 1;
			wait1Msec(1);
			} else if(vexRT[Btn7R]) {
			motor[scooper] = motor[scooper] - 1;
			wait1Msec(1);
		}

		if(vexRT[Btn8U]) {
			motor[cart] = motor[cart] + 1;
			wait1Msec(1);
			} else if(vexRT[Btn8D]) {
			motor[cart] = motor[cart] - 1;
			wait1Msec(1);
		}

		if(vexRT[Btn7U]) {
			motor[cart2] = motor[cart2] - 1;
			wait1Msec(1);
			} else if(vexRT[Btn7D]) {
			motor[cart2] = motor[cart2] + 1;
			wait1Msec(1);
		}
	}
}

task main() {
	startTask(drive);
	startTask(manipulator);
	while(on) {
		rightX = vexRT(Ch1);
		rightY = vexRT(Ch2);
		leftY = vexRT(Ch3);
		leftX = vexRT(Ch4);
	}
}
//BANG!!!
