#pragma config(Motor,  port2,           driveL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           lifter,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           clawR,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           clawL,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           cart,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           driveR,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftX = 0;
int leftY = 0;
int rightY = 0;
int rightX = 0;
const bool on = true;

task drive() {
	while(on) {
		motor[driveL] = rightY + rightX;
		motor[driveR] = rightY - rightX;
	}
}

task manipulator() {
	while(on) {

	}
}

task main() {
	startTask(drive);
	startTask(manipulator);
	while(on) {
		rightX = vexRT(Ch1);
		rightY = vexRT(Ch2);
		leftY = vexRT(Ch3);
		leftX = vexRT(Ch4);
	}
}
