#pragma config(Motor,  port2,           driveL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           boxS,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           claw,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           rotate1,       tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           rotate2,       tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           box,           tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           driveR,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*WARNING DON'T FIX THE FORMATTING

    /***********************************\
   /                  The                \
  /           Home of Programming         \
 /                                         \
/                                           \
| Right joystick =  Drive                   |
|                                           |
| Button 6U + left joystick = arm up & down |
|                                           |
| Button 6D = Holds the arm position        |
|                                           |
| Button 5U = Open Dumper                   |
|                                           |
| Button 5D = Close Dumper                  |
|*******************************************/

/*********************************************************\
|This is the best code ;) for the 2015 BEST competition.  |
|Written by: Programmers. If you need help programming,   |
|ask the main programmers(Dalton,and George).             |
|They would be happy to help you, but if they cannot help |
|for any reason they will assign a subordinate to assist  |
|you.                                                     |
|                                               Thank You.|
\*********************************************************/


int leftX = 0;
int leftY = 0;
int rightY = 0;
int rightX = 0;
int thresh = 15;
int stage = 0;
bool macro = false;
const bool on = true;

task drive() {
	while(on) {
		motor[driveL] = -rightY - rightX;
		motor[driveR] = rightY - rightX;
	}
}

task manipulator() {
	while(on) {
		if(vexRT[Btn6U]) {
			if(vexRT[Btn6D]) {
				motor[arm] = leftY + 20;
				} else {
				motor[arm] = leftY;
			}
			} else if(vexRT[Btn6D]) {
			motor[arm] = 20;
			} else {
			motor[arm] = 0;
		}

		if(vexRT[Btn8L]) {

			motor[claw] = motor[claw] + 1;
			wait1Msec(1);
			} else if(vexRT[Btn8R]) {
			motor[claw] = motor[claw] - 1;
			wait1Msec(1);
		}

		if(vexRT[Btn7L]) {
			motor[rotate1] = motor[rotate1] + 1;
			wait1Msec(1);
			} else if(vexRT[Btn7R]) {
			motor[rotate1] = motor[rotate1] - 1;
			wait1Msec(1);
		}

		if(vexRT[Btn5U] && stage == 0) {
			motor[boxS] = -55;
			macro = true;
			stage = 1;
		} else if(vexRT[Btn5D] && stage == 1 && macro == false) {
			motor[boxS] = -127;
			stage = 2;
		} else if(!vexRT[Btn5U] && macro == true && stage == 1) {
			macro = false;
		}

		if(vexRT[Btn7U]) {
			motor[rotate2] = motor[rotate2] - 1;
			wait1Msec(1);
			} else if(vexRT[Btn7D]) {
			motor[rotate2] = motor[rotate2] + 1;
			wait1Msec(1);
		}

		if(vexRT[Btn5D]) {
			motor[box] = 120;
			} else if(vexRT[Btn5U]) {
			motor[box] = -120;
			} else {
			motor[box] = 0;
		}

		if(vexRT[Btn8D] && macro == false) {
			macro = true;
			motor[arm] = 100;
			wait1Msec(80);
			motor[arm] = 0;
			} else if(vexRT[Btn8U] && macro == false) {
			macro = true;
			motor[arm] = 75;
			wait1Msec(80);
			motor[arm] = 0;
			} else if(macro == true && !vexRT[Btn8D] && !vexRT[Btn8U]) {
			macro = false;
		}

/*		if(vexRT[Btn7L] && macro == false) {
			macro = true;
			motor[arm] = 100;
			motor[box] = -120;
			wait1Msec(150);
			motor[arm] = 0;
			wait1Msec(500);
			motor[box] = 0;
			} else if(macro == true && !vexRT[Btn7L]) {
			macro = false;
		}*/
	}
}

task main() {
	startTask(drive);
	startTask(manipulator);
	while(on) {
		rightX = vexRT(Ch1);
		if(abs(rightX)<thresh){
			rightX = 0;
		}
		rightY = vexRT(Ch2);
		if(abs(rightY)<thresh){
			rightY = 0;
		}
		leftY = vexRT(Ch3);
		if(abs(leftY)<thresh){
			leftY = 0;
		}
		leftX = vexRT(Ch4);
		if(abs(leftX)<thresh){
			leftX = 0;
		}
	}
}
//BANG!!! and thats how its done.
